version: "3.9"

services:

  backend:

    build:

      context: .

      dockerfile: backend.Dockerfile

    container_name: intelligent-log-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped

  frontend:

    build:

      context: .

      dockerfile: frontend.Dockerfile

    container_name: intelligent-log-frontend

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      - backend

    restart: unless-stopped